### ISSUE TITLE
Missing WebDavFileInfoBase Directive

### ISSUE THREAD

**Issue by ghost** [Winterleaf/Winterleaf-WebDavSharp.SQLExample#1]
Hey there,
I just cloned this repository, added a reference to the nu-get package of WebDAVSharp.Server and tried to build. Now, I have like 300 errors of missing directives or assembly references.
(For eg.: In WebDAVSharp.Data:SqlStoreFileInfo the base class 'WebDavFileInfoBase' is missing, and I cant find any existance of it (nor in this and neither in the WebDAVSharp.Server repo).

Is it possible this repository is outdated and doesnt work with newer version of WebDAVSharp.Server or am I missing something obvious ?

**Comment by ghost** [comment]
Can be closed, i was missing something (more or less) obvious !
I didnt recognized your pull request at `WebDAVSharp.Server` which implemented the missing files. 

To use this repo one need a build of `WebDAVSharp.Server` from `development` branch since the pull request isnt integrated in the `master` branch. Maybe a notify in the readme, that the official nu-get package of `WebDAVSharp.Server` doesnt work until your pull request got its way into the `master` branch would be helpful (incase there are more meatheads than me).

**Comment by Winterleaf** [comment]
Hey there, I actually have a massive update to the system, I built a web interface for it so you can access stuff via web or webdav.

Handles security, searching, notation, and such, I’ll see if I can push the update.
